DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
      FROM USER_TAB_COLS
     WHERE TABLE_NAME = 'TB_FRETE'
       AND COLUMN_NAME = 'SERVICO_FRETE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TB_FRETE ADD (SERVICO_FRETE VARCHAR2(120) DEFAULT ''Nao informado'' NOT NULL)';
    END IF;
END;
/
